### ISSUE TITLE
Url_list

### ISSUE THREAD

**Issue by anew42** [whoisoscar/calameo-downloader#3]
Hi! I'm new here, french and not really used to python....
So, i have this problem : 
book_url_list = [fr.calameo.com/read/0051072...]
                                                   ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

And if i write url with https://,  i have this message :  ModuleNotFoundError: No module named 'requests'

So, how can i fix this problem?
And after, which sign to use to put multiple url? 
Sorry for the approximativ language
Sat

**Comment by whoisoscar** [comment]
Hey there Sat!

The variable _book_url_list_ is a list of integers. Therefore to insert urls, please paste them in the following format:
["https://exampleurl1", "https://exampleurl2", "https://exampleurl3"]

Make sure to have the https:// in the url as it will not work otherwise.
Strings are represented by quotations in Python, and list items are separated by comas.

Hope this helped,
Oscar

**Comment by anew42** [comment]
Thanks! So... i was on the right way on my first try.

-> I have this message :

Traceback (most recent call last):
   File "C:\Users\festi\calameo-downloader\main.py", line 1, in <module>
     import requests
ModuleNotFoundError: No module named 'requests'

Is it a module not installed on my computer?

Sat

Le 10/06/2021 à 00:46, Oscar a écrit :

**Comment by whoisoscar** [comment]
Sorry for the late response.

Please follow the project docs to get it working.

Make sure to install all the required modules by doing the following:

> pip install -r requirements.txt

Any other issues should be easily resolved through google searches and results on stackoverflow; otherwise feel free to reply to this comment :)

Oscar
